# Generated by Django 4.2.11 on 2024-05-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='photo',
        ),
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
